language: ruby
rvm:
- 2.1
- 2.0.0
before_script: bundle exec berks install
script: bundle exec strainer test --except kitchen
notifications:
  slack:
    secure: Qbv+bWThk0LbOkPNnd9l1MUOba/P3+YdoxAlaWpOXwK0vcMAA9chJDDl9IFFrePdVyAafFEMODHpMdySNb26Z1iwhz3YEFDUjJOC2tY3Mlos2OEa4AzaxPBsXBFdrnciPTv4TuawIgwoBJm6TsHa4cjpfsh5aCdnIW8dqJJHksy8AiG8DSR3wM/MROJ+tXXaQsfzj8upVs5OSSFtfzgg9m4hBM3gjD87+M7jrdTEUN6hXjEHrUER7DeeS6SZ8m5GUtwWCBIztQyNs0YsIdbUm3IqmbZnyEUkB+j3uSrVLMgB9CQyCMJyTQxVzMRzgVqsfmtWiyfWTUM0EJ6Xj8Mob1McS4vFPufbhADLOLWQbCxsXichnb7FIMqPoGUlqeOlyHHDivsKGeOloC5UM17DIU1b6tjtQcAKjGW2rzUViWBrh5TAwsYlL+Q9u+Qm7/yUVyd3clVjUHRGqowLl+ofsRIKcu8sLPK+r4Y9iQvTD2SwFOstyVogEIOH6TcK/zsrPMr/4Vt6Bti3IURDrgNvusr+3Z8AEnuXKc1K+KCR5VHG4RlcezSn7NAEUd8JV562Xx2jJy1G1s2X+1jCYepmJV7nxRMBp9qJNkwTA92gs8M8+OWcpsWk9dHl7mexdXArzArRbB5geyUqvyVTGQbeLaVgNc9p4w3yQEipLNaJp/Y=
